services:
  app:
    build:
      args:
        user: site-user
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: site
    container_name: site
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - site
    restart: always
  mysql:
    image: mysql:8.0.29
    container_name: site-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - site
    restart: always
  nginx:
    image: nginx:alpine
    container_name: site-nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx_local:/etc/nginx/conf.d/
    networks:
      - site
    restart: always
networks:
  site:
    driver: bridge
volumes:
  mysql:
    driver: local